# Generated by Django 6.0.2 on 2026-02-17 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimetableSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "room",
                    models.CharField(
                        blank=True,
                        help_text="Room or lab number e.g. A-101",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "effective_from",
                    models.DateField(help_text="Date from which this slot is active"),
                ),
                (
                    "effective_to",
                    models.DateField(
                        blank=True, help_text="Leave blank if ongoing", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_slots",
                        to="academic.section",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_slots",
                        to="academic.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_slots",
                        to="accounts.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timetable Slot",
                "verbose_name_plural": "Timetable Slots",
                "ordering": ["day_of_week", "start_time"],
                "unique_together": {("section", "day_of_week", "start_time")},
            },
        ),
    ]
