# Generated by Django 6.0.2 on 2026-02-17 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0002_timetableslot"),
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimetableChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("reschedule", "Reschedule Class"),
                            ("substitute", "Request Substitute"),
                            ("cancel", "Cancel Class"),
                            ("room", "Change Room"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Explain why this change is needed"),
                ),
                (
                    "requested_date",
                    models.DateField(
                        blank=True,
                        help_text="Which specific date needs the change",
                        null=True,
                    ),
                ),
                (
                    "proposed_time",
                    models.TimeField(
                        blank=True,
                        help_text="New proposed start time (for reschedule)",
                        null=True,
                    ),
                ),
                (
                    "proposed_room",
                    models.CharField(
                        blank=True,
                        help_text="New proposed room (for room change)",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "management_note",
                    models.TextField(
                        blank=True,
                        help_text="Management response or reason for rejection",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="accounts.teacher",
                    ),
                ),
                (
                    "timetable_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="academic.timetableslot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timetable Change Request",
                "verbose_name_plural": "Timetable Change Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
