# Generated by Django 6.0.1 on 2026-02-12 18:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "topic",
                    models.CharField(
                        blank=True,
                        help_text="Topic covered in this session",
                        max_length=200,
                    ),
                ),
                (
                    "attendance_marked",
                    models.BooleanField(
                        default=False,
                        help_text="Has attendance been marked for this session?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_sessions",
                        to="academic.section",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_sessions",
                        to="academic.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_sessions",
                        to="accounts.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class Session",
                "verbose_name_plural": "Class Sessions",
                "ordering": ["-date", "-start_time"],
                "unique_together": {("date", "subject", "section", "start_time")},
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_present", models.BooleanField(default=False)),
                ("marked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "remarks",
                    models.CharField(
                        blank=True,
                        help_text="Optional remarks (e.g., Late, Medical Leave)",
                        max_length=200,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="accounts.student",
                    ),
                ),
                (
                    "class_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="attendance.classsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendance Records",
                "ordering": ["-marked_at"],
                "unique_together": {("class_session", "student")},
            },
        ),
    ]
