# Generated by Django 6.0.2 on 2026-02-17 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0002_timetableslot"),
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classsession",
            options={
                "ordering": ["-date", "start_time"],
                "verbose_name": "Class Session",
                "verbose_name_plural": "Class Sessions",
            },
        ),
        migrations.AddField(
            model_name="classsession",
            name="cancellation_note",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="classsession",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="classsession",
            name="room",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="classsession",
            name="timetable_slot",
            field=models.ForeignKey(
                blank=True,
                help_text="The recurring slot this session was generated from",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_sessions",
                to="academic.timetableslot",
            ),
        ),
        migrations.AlterField(
            model_name="classsession",
            name="attendance_marked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="classsession",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="classsession",
            name="topic",
            field=models.CharField(
                blank=True,
                help_text="Topic covered — teacher fills this when marking attendance",
                max_length=200,
            ),
        ),
    ]
