# Generated by Django 6.0.2 on 2026-02-21 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0003_timetablechangerequest"),
        ("attendance", "0002_alter_classsession_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="classsession",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="classsession",
            name="is_remedial",
            field=models.BooleanField(
                default=False,
                help_text="True if this is a makeup/remedial class scheduled by teacher",
            ),
        ),
        migrations.AddField(
            model_name="classsession",
            name="original_session",
            field=models.ForeignKey(
                blank=True,
                help_text="If remedial, which session is this making up for?",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="remedial_classes",
                to="attendance.classsession",
            ),
        ),
        migrations.AddField(
            model_name="classsession",
            name="remedial_reason",
            field=models.CharField(
                blank=True,
                help_text="Why was this remedial class needed?",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="classsession",
            name="timetable_slot",
            field=models.ForeignKey(
                blank=True,
                help_text="The recurring slot this session was generated from (null for remedial classes)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_sessions",
                to="academic.timetableslot",
            ),
        ),
    ]
